---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template to setup CFN Stackset roles in the Target account and enable use of the account as a target account in AWS CloudFormation StackSets.'

### Parameters
Parameters:
  pAdministratorAccountId:
    Type: String
    Description: AWS Account Id of the administrator account (the account in which StackSets will be created)
    MaxLength: 12
    MinLength: 12

### Resources
Resources:
  rStackSetExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSCloudFormationStackSetExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref pAdministratorAccountId
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess