---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template to create cross account policy for gaining access in the Member account using STS.'

### Parameters
Parameters:
  pMasterAwsAccountId:
    Description: Account ID of the Master AWS Account
    Type: Number
    ConstraintDescription: Must be a valid AWS Account ID
    MaxValue: 999999999999
    MinValue: 111111111111
  pChildAccountAlias:
    Description: Alias for the child account
    Type: String
  pMaxApiSessionDuration:
    Description: Session duration for CLI / API in seconds (Min - 1hr, Max - 12 hrs)
    Type: Number
    MaxValue: 43200
    MinValue: 3600
    Default: 3600
  pAllowReadOnlyWithBilling:
    Description: Enables or disables the Read Only With Billing Role
    Type: String
    Default: "Yes"
    AllowedValues:
      - "Yes"
      - "No"
  pAllowPowerUserAccess:
    Description: Enables or disables the Power User Role
    Type: String
    Default: "Yes"
    AllowedValues:
      - "Yes"
      - "No"
  pAllowAdminAccess:
    Description: Enables or disables the Administrator Role
    Type: String
    Default: "Yes"
    AllowedValues:
      - "Yes"
      - "No"

### Conditions
Conditions:
  cCreateReadOnlyWithBillingRole: !Equals [!Ref pAllowReadOnlyWithBilling, "Yes"]
  cCreatePowerUserAccessRole: !Equals [!Ref pAllowPowerUserAccess, "Yes"]
  cCreateAdminAccessRole: !Equals [!Ref pAllowAdminAccess, "Yes"]

### Resources
Resources:
  rRoleReadOnlyAccess:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              AWS: !Sub
                - arn:aws:iam::${MasterAccountID}:root
                - {MasterAccountID: !Ref pMasterAwsAccountId}
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/ReadOnlyAccess"
      MaxSessionDuration: !Ref pMaxApiSessionDuration
  rRoleReadOnlyWithBillingAccess:
    Type: "AWS::IAM::Role"
    Condition: cCreateReadOnlyWithBillingRole
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              AWS: !Sub
                - arn:aws:iam::${MasterAccountID}:root
                - {MasterAccountID: !Ref pMasterAwsAccountId}
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/ReadOnlyAccess"
        - "arn:aws:iam::aws:policy/job-function/Billing"
      MaxSessionDuration: !Ref pMaxApiSessionDuration
  rPowerUserAccess:
    Type: "AWS::IAM::Role"
    Condition: cCreatePowerUserAccessRole
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              AWS: !Sub
                - arn:aws:iam::${MasterAccountID}:root
                - {MasterAccountID: !Ref pMasterAwsAccountId}
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/PowerUserAccess"
      MaxSessionDuration: !Ref pMaxApiSessionDuration
  rAdministratorAccess:
    Type: "AWS::IAM::Role"
    Condition: cCreateAdminAccessRole
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              AWS: !Sub
                - arn:aws:iam::${MasterAccountID}:root
                - {MasterAccountID: !Ref pMasterAwsAccountId}
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
      MaxSessionDuration: !Ref pMaxApiSessionDuration
  rAccountAliasSSMStore:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: Account Alias in IAM
      Name: account-alias
      Type: String
      Value: !Ref pChildAccountAlias
### Outputs
Outputs:
  oRoleReadOnlyAccess:
    Description: Read Only Cross Account Role Signin Link
    Value:
      "Fn::Sub": |
        https://signin.aws.amazon.com/switchrole?account=${AWS::AccountId}&roleName=${rRoleReadOnlyAccess}&displayName=x-read-only@${pChildAccountAlias}
  oRoleReadOnlyWithBillingAccess:
    Description: Read Only with Billing Cross Account Role Signin Link
    Condition: cCreateReadOnlyWithBillingRole
    Value:
      "Fn::Sub": |
        https://signin.aws.amazon.com/switchrole?account=${AWS::AccountId}&roleName=${rRoleReadOnlyWithBillingAccess}&displayName=x-read-only-wbilling@${pChildAccountAlias}
  oPowerUserAccess:
    Description: Power User Account Role Signin Link
    Condition: cCreatePowerUserAccessRole
    Value:
      "Fn::Sub": |
        https://signin.aws.amazon.com/switchrole?account=${AWS::AccountId}&roleName=${rPowerUserAccess}&displayName=x-poweruser@${pChildAccountAlias}
  oAdministratorAccess:
    Description: Administrator Account Role Signin Link
    Condition: cCreateAdminAccessRole
    Value:
      "Fn::Sub": |
        https://signin.aws.amazon.com/switchrole?account=${AWS::AccountId}&roleName=${rAdministratorAccess}&displayName=x-administrator@${pChildAccountAlias}

